name: Build Windows
run-name: Build Windows
on:
  workflow_dispatch: {}
jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: |
          choco install python --version=3.9.7
          python -m pip install --upgrade pip
      - name: Download Chinese language files
        run: |
          Invoke-WebRequest -Uri "https://raw.github.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "ChineseSimplified.isl"
          Move-Item -Path "ChineseSimplified.isl" -Destination "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"
      - run: python3 windows/build_windows.py
      - uses: actions/upload-artifact@v4
        with:
          name: windows_build
          path: build/windows/x64/release/

